database:
  driverClass: com.aerospike.jdbc.AerospikeDriver
  url: jdbc:aerospike:127.0.0.1:3000/test
  validationQuery: "select * from ns1 limit 1"

logging:
  level: INFO
  loggers:
    io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: DEBUG
    com.aerospike.jdbc: WARN
  appenders:
    - type: console
      #logFormat: "%yellow(%d{ISO8601}) %highlight(%-5level) [%white(%t)] %green(%logger{-20.20}): %m%n%boldRed(%ex{short})"

presidio:
  analyzer:
    host: 127.0.0.1
    port: 5001
    score_threshold: 0.5
  anonymizer:
    host: 127.0.0.1
    port: 5002

recorder:
  anonyimized:
    enabled: true
    namespace: test
  raw:
    enabled: false
    namespace: rawRecords
